<div class="columns one-column">
    <div class="panel">
        <h1>Change Password</h1>

        <p>
            Current Password<br>
            <input type="password" name="current-password">
        </p>

        <p>
            New Password<br>
            <input type="password" name="new-password">
        </p>

        <p>
            Confirm New Password<br>
            <input type="password" name="confirm-new-password">
        </p>

        <input type="hidden" name="https-token" value="https-token-will-go-here">

        <input type="submit" value="Change Password">
    </div>
</div>
