<div class="columns one-column">
    <div class="panel">
        <h1>Change Password</h1>

        <form action="/account/change-password" method="post">

        <p>
            Current Password<br>
            <input type="password" name="current-password">
        </p>

        <p>
            New Password<br>
            <input type="password" name="new-password">
        </p>

        <p>
            Confirm New Password<br>
            <input type="password" name="confirm-new-password">
        </p>

        <input type="hidden" name="https-token" value="<?= $this->escape($user->getHttpsToken()); ?>">

        <input type="submit" value="Change Password">

        </form>
    </div>
</div>
